[package]
name = "matter"
version = "0.1.0"
authors = ["Remco Bloemen <remco@0x.org>"]
edition = "2018"

[dependencies]
ff = { package = "ff_ce", version = "0.6", features = ["derive"] }
serde = { version = "1.0.80", features = ["derive"] }
hex = "0.4.0"
rand = "0.4.0"
